### ISSUE TITLE
Reapply config for failed VMs on Azure

### ISSUE THREAD

**Issue by stoyanr** [gardener/remedy-controller#3]
**Issue**

From time to time we see failed VMs on Azure. Sometimes this can be fixed by retrieving the config for the machine and re-applying it. Since re-applying the config does not always fix the issue, we should also alert the Operator of the Week if the VM remains in the failed state.

**Proposed solution**

1. In a controller, monitor `Node` objects that are not ready and/or unreachable, or use another appropriate mechanism to identify `Failed` VMs, taking care to limit calls to Azure due to rate limits.
2. Track VMs via a custom resource, e.g. `VirtualMachine`. Run the `reapply` operation on such VMs as part of the reconciliation of this resource if `provisioningState: Failed` is detected. Retry this several times on failure, perhaps with backoff.
3. For VMs that remain in `Failed` state, raise an alert.

**References**

Relevant Azure API documentation (Go SDK should provide similar methods/fields):
* [Get VM state](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get)
* [Reapply VM configuration](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/reapply)

**Tasks**

* [x] Reliably reproduce or simulate the issue, if needed via a special script / binary
* [x] Implement Azure node controller
* [x] Implement Azure virtualmachine controller
  - [x] Enhance handling of Azure errors to avoid unlimited retries and hitting rate limits
  - [x] Raise an alert if the number of max attempts to reapply a VM is exhausted (#9)
* [x] Update scripts for testing the Azure remedy controller (#8)
* [x] Update Concourse pipeline for Azure remedy controller tests (#8)

**Comment by stoyanr** [comment]
All tasks finished now, closing this epic.
