### ISSUE TITLE
Cleanup Azure orphaned public IPs

### ISSUE THREAD

**Issue by stoyanr** [gardener/remedy-controller#6]
Implement a controller manager for Azure and all needed controllers to handle orphaned public IPs in Azure.

* [x] Add remedy controller manager skeleton
* [x] Implement Azure service controller
* [x] Implement Azure pulbicipaddress controller
  - [x] Make requeue intervals and timeouts configurable
  - [x] Specify the actual IP address in the publicipaddress spec instead of the name
  - [x] Enhance handling of Azure errors to avoid unlimited retries and hitting rate limits
* [x] Add scripts for testing the Azure remedy controller
* [x] Add Helm charts for installing the Azure remedy controller
* [x] Create Concourse pipeline for Azure remedy controller tests
* [x] Add unit tests for the Azure controller actuators and the generic reconciler
* [x] Add metrics for cleaned up IP addresses and Azure read / write requests
* [x] Extract Azure utilities into their own type(s)
* [x] Rollout Azure remedy controller to Azure shoots using Gardener extensions (#7)
* [x] Maintain custom resources in a control cluster different from the target cluster
* [x] Add a README to document the functionality and usage of the controller

**Comment by stoyanr** [comment]
All tasks are finished now. There is an open issue #32, but it can be tracked independently of this epic. Closing this epic.
